# This file should contain everything to configure the workflow on a global scale.
# It should be complemented by a samples.tsv file that contains one row per sample.
# The units.tsv file should contain the location of each project folder
# (containing fastq files).

# -- 1. Samples configuration -- #
samples: "config/samples.tsv"
units: "config/units.tsv"
out: "/data/gpfs-1/users/cofu10_c/scratch/lofreq/out"
log: "/data/gpfs-1/users/cofu10_c/scratch/lofreq/log" 

genome_reference: "/data/gpfs-1/users/cofu10_c/work/references/genome/GRCh38.u2af1_fix.v1.2020_04_01.fa"
region_file: "/data/gpfs-1/users/cofu10_c/work/references/regions/probes_merged_Charite_CH-CLL_TE-91254749_hg38.bed"
dbsnp: "/data/gpfs-1/users/cofu10_c/work/references/annotations/dbsnp.vcf.gz"

# -- Cluster resources configuration -- #
resources:
    default:
        threads: 1
        walltime: 480
        mem_mb: 8000
    lofreq:
        threads: 2
        mem_mb: 120000
        walltime: 7200
